### ISSUE TITLE
To-do-list: Peer to peer review

### ISSUE THREAD

**Issue by PeteUgwu** [187jjay187/to-do-list-review#2]
## Required Changes♻
You have done so great! Cheers🥂
However, in a bid to adhere to the best practices, I found the following piece/line of code that can be improved on;

- [ ] Don't you think this line of [code](https://github.com/187jjay187/to-do-list-review/blob/b0051a3ebece1acccc682224c1584aed207fc1ba/src/style.css#L19) would be better if written this way "margin: 300px auto auto;"?. This would make it look [DRY](https://github.com/microverseinc/curriculum-transversal-skills/blob/main/clean-code/exercise_it_is_DRY.md) and still perform the same function.

https://github.com/187jjay187/to-do-list-review/blob/b0051a3ebece1acccc682224c1584aed207fc1ba/src/style.css#L19

**Comment by 187jjay187** [comment]
Thank you for the code review, I'm sure you will find all suggested changes have been made.
